# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 550)
        MainWindow.setMinimumSize(QtCore.QSize(368, 250))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setStyleSheet("background-color: lightblue;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 50, 306, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.SubstrateYieldStressLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SubstrateYieldStressLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SubstrateYieldStressLabel_2.setObjectName("SubstrateYieldStressLabel_2")
        self.gridLayout.addWidget(self.SubstrateYieldStressLabel_2, 12, 0, 1, 1)
        self.JointWidthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.JointWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.JointWidthLabel.setObjectName("JointWidthLabel")
        self.gridLayout.addWidget(self.JointWidthLabel, 9, 0, 1, 1)
        self.AdModLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdModLineEdit.setEnabled(True)
        self.AdModLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdModLineEdit.setObjectName("AdModLineEdit")
        self.gridLayout.addWidget(self.AdModLineEdit, 1, 1, 1, 1)
        self.OverlapLengthmm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.OverlapLengthmm.setAlignment(QtCore.Qt.AlignCenter)
        self.OverlapLengthmm.setObjectName("OverlapLengthmm")
        self.gridLayout.addWidget(self.OverlapLengthmm, 6, 2, 1, 1)
        self.JointWidtmm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.JointWidtmm.setAlignment(QtCore.Qt.AlignCenter)
        self.JointWidtmm.setObjectName("JointWidtmm")
        self.gridLayout.addWidget(self.JointWidtmm, 9, 2, 1, 1)
        self.AdhesiveYieldStressLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdhesiveYieldStressLineEdit.setEnabled(True)
        self.AdhesiveYieldStressLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveYieldStressLineEdit.setObjectName("AdhesiveYieldStressLineEdit")
        self.gridLayout.addWidget(self.AdhesiveYieldStressLineEdit, 10, 1, 1, 1)
        self.AdhesiveShearModulusLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdhesiveShearModulusLineEdit.setEnabled(True)
        self.AdhesiveShearModulusLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveShearModulusLineEdit.setObjectName("AdhesiveShearModulusLineEdit")
        self.gridLayout.addWidget(self.AdhesiveShearModulusLineEdit, 15, 1, 1, 1)

        self.ThroughThincknessLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ThroughThincknessLineEdit.setEnabled(True)
        self.ThroughThincknessLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ThroughThincknessLineEdit.setObjectName("ThroughThincknessLineEdit")
        self.gridLayout.addWidget(self.ThroughThincknessLineEdit, 18, 1, 1, 1)

        self.InterlaminarShearStrengthLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.InterlaminarShearStrengthLineEdit.setEnabled(True)
        self.InterlaminarShearStrengthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.InterlaminarShearStrengthLineEdit.setObjectName("InterlaminarShearStrengthLineEdit")
        self.gridLayout.addWidget(self.InterlaminarShearStrengthLineEdit, 19, 1, 1, 1)

        self.AdherendShearModulusLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdherendShearModulusLineEdit.setEnabled(True)
        self.AdherendShearModulusLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdherendShearModulusLineEdit.setObjectName("AdherendShearModulusLineEdit")
        self.gridLayout.addWidget(self.AdherendShearModulusLineEdit, 16, 1, 1, 1)

        self.AdhesiveYieldStrengthLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdhesiveYieldStrengthLineEdit.setEnabled(True)
        self.AdhesiveYieldStrengthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveYieldStrengthLineEdit.setObjectName("AdhesiveYieldStrengthLineEdit")
        self.gridLayout.addWidget(self.AdhesiveYieldStrengthLineEdit, 17, 1, 1, 1)

        self.AdShearModGPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdShearModGPa.setAlignment(QtCore.Qt.AlignCenter)
        self.AdShearModGPa.setObjectName("AdShearModGPa")
        self.gridLayout.addWidget(self.AdShearModGPa, 8, 2, 1, 1)
        self.AdThickLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdThickLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdThickLabel_2.setObjectName("AdThickLabel_2")
        self.gridLayout.addWidget(self.AdThickLabel_2, 3, 0, 1, 1)
        self.AdhesiveThickLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdhesiveThickLineEdit.setEnabled(True)
        self.AdhesiveThickLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveThickLineEdit.setObjectName("AdhesiveThickLineEdit")
        self.gridLayout.addWidget(self.AdhesiveThickLineEdit, 7, 1, 1, 1)
        self.SubstrateShearYieldStressLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SubstrateShearYieldStressLineEdit.setEnabled(True)
        self.SubstrateShearYieldStressLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.SubstrateShearYieldStressLineEdit.setObjectName("SubstrateShearYieldStressLineEdit")
        self.gridLayout.addWidget(self.SubstrateShearYieldStressLineEdit, 11, 1, 1, 1)
        self.Substrate2ndYieldStressLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Substrate2ndYieldStressLineEdit.setEnabled(True)
        self.Substrate2ndYieldStressLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Substrate2ndYieldStressLineEdit.setObjectName("Substrate2ndYieldStressLineEdit")
        self.gridLayout.addWidget(self.Substrate2ndYieldStressLineEdit, 13, 1, 1, 1)
        self.SubstrateYieldStressMPa_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SubstrateYieldStressMPa_2.setAlignment(QtCore.Qt.AlignCenter)
        self.SubstrateYieldStressMPa_2.setObjectName("SubstrateYieldStressMPa_2")
        self.gridLayout.addWidget(self.SubstrateYieldStressMPa_2, 12, 2, 1, 1)
        self.BaseAdThickLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.BaseAdThickLineEdit.setEnabled(True)
        self.BaseAdThickLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.BaseAdThickLineEdit.setObjectName("BaseAdThickLineEdit")
        self.gridLayout.addWidget(self.BaseAdThickLineEdit, 3, 1, 1, 1)
        self.AdhesiveYieldStressMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveYieldStressMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveYieldStressMPa.setObjectName("AdhesiveYieldStressMPa")
        self.gridLayout.addWidget(self.AdhesiveYieldStressMPa, 10, 2, 1, 1)
        self.AdhesiveShearModulusMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveShearModulusMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveShearModulusMPa.setObjectName("AdhesiveShearModulusMPa")
        self.gridLayout.addWidget(self.AdhesiveShearModulusMPa, 15, 2, 1, 1)

        self.ThroughThincknessMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ThroughThincknessMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.ThroughThincknessMPa.setObjectName("ThroughThincknessMPa")
        self.gridLayout.addWidget(self.ThroughThincknessMPa, 18, 2, 1, 1)

        self.InterlaminarShearStrengthMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.InterlaminarShearStrengthMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.InterlaminarShearStrengthMPa.setObjectName("InterlaminarShearStrengthMPa")
        self.gridLayout.addWidget(self.InterlaminarShearStrengthMPa, 19, 2, 1, 1)

        self.AdherendShearModulusMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdherendShearModulusMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.AdherendShearModulusMPa.setObjectName("AdherendShearModulusMPa")
        self.gridLayout.addWidget(self.AdherendShearModulusMPa, 16, 2, 1, 1)

        self.AdhesiveYieldStrengthMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveYieldStrengthMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveYieldStrengthMPa.setObjectName("AdhesiveYieldStrengthMPa")
        self.gridLayout.addWidget(self.AdhesiveYieldStrengthMPa, 17, 2, 1, 1)

        self.OverlapLengthLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.OverlapLengthLineEdit.setEnabled(True)
        self.OverlapLengthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.OverlapLengthLineEdit.setObjectName("OverlapLengthLineEdit")
        self.gridLayout.addWidget(self.OverlapLengthLineEdit, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 13, 0, 1, 1, QtCore.Qt.AlignRight)
        self.TopAdThickLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.TopAdThickLineEdit.setEnabled(True)
        self.TopAdThickLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.TopAdThickLineEdit.setObjectName("TopAdThickLineEdit")
        self.gridLayout.addWidget(self.TopAdThickLineEdit, 2, 1, 1, 1)
        self.PRatioLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.PRatioLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PRatioLabel.setObjectName("PRatioLabel")
        self.gridLayout.addWidget(self.PRatioLabel, 5, 0, 1, 1)
        self.AdShearModLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdShearModLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdShearModLabel.setObjectName("AdShearModLabel")
        self.gridLayout.addWidget(self.AdShearModLabel, 8, 0, 1, 1)
        self.LoadLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LoadLineEdit.setEnabled(True)
        self.LoadLineEdit.setMaxLength(32767)
        self.LoadLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.LoadLineEdit.setClearButtonEnabled(False)
        self.LoadLineEdit.setObjectName("LoadLineEdit")
        self.gridLayout.addWidget(self.LoadLineEdit, 0, 1, 1, 1)
        self.SubstrateYieldStressLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SubstrateYieldStressLineEdit.setEnabled(True)
        self.SubstrateYieldStressLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.SubstrateYieldStressLineEdit.setObjectName("SubstrateYieldStressLineEdit")
        self.gridLayout.addWidget(self.SubstrateYieldStressLineEdit, 12, 1, 1, 1)
        self.SubstrateYieldStressMPa_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SubstrateYieldStressMPa_3.setAlignment(QtCore.Qt.AlignCenter)
        self.SubstrateYieldStressMPa_3.setObjectName("SubstrateYieldStressMPa_3")
        self.gridLayout.addWidget(self.SubstrateYieldStressMPa_3, 13, 2, 1, 1)
        self.AdShearModLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AdShearModLineEdit.setEnabled(True)
        self.AdShearModLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.AdShearModLineEdit.setObjectName("AdShearModLineEdit")
        self.gridLayout.addWidget(self.AdShearModLineEdit, 8, 1, 1, 1)
        self.JointWidthLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.JointWidthLineEdit.setEnabled(True)
        self.JointWidthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.JointWidthLineEdit.setObjectName("JointWidthLineEdit")
        self.gridLayout.addWidget(self.JointWidthLineEdit, 9, 1, 1, 1)
        self.PRatioLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.PRatioLineEdit.setEnabled(True)
        self.PRatioLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PRatioLineEdit.setObjectName("PRatioLineEdit")
        self.gridLayout.addWidget(self.PRatioLineEdit, 5, 1, 1, 1)
        self.AdhesiveThickmm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveThickmm.setAlignment(QtCore.Qt.AlignCenter)
        self.AdhesiveThickmm.setObjectName("AdhesiveThickmm")
        self.gridLayout.addWidget(self.AdhesiveThickmm, 7, 2, 1, 1)
        self.OverlapLengthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.OverlapLengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OverlapLengthLabel.setObjectName("OverlapLengthLabel")
        self.gridLayout.addWidget(self.OverlapLengthLabel, 6, 0, 1, 1)
        self.AdModLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdModLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdModLabel.setObjectName("AdModLabel")
        self.gridLayout.addWidget(self.AdModLabel, 1, 0, 1, 1)
        self.SubstrateYieldStressMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SubstrateYieldStressMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.SubstrateYieldStressMPa.setObjectName("SubstrateYieldStressMPa")
        self.gridLayout.addWidget(self.SubstrateYieldStressMPa, 11, 2, 1, 1)
        self.LoadN = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LoadN.setAlignment(QtCore.Qt.AlignCenter)
        self.LoadN.setObjectName("LoadN")
        self.gridLayout.addWidget(self.LoadN, 0, 2, 1, 1)
        self.SubstrateYieldStressLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SubstrateYieldStressLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SubstrateYieldStressLabel.setObjectName("SubstrateYieldStressLabel")
        self.gridLayout.addWidget(self.SubstrateYieldStressLabel, 11, 0, 1, 1)
        self.LoadLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LoadLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LoadLabel.setObjectName("LoadLabel")
        self.gridLayout.addWidget(self.LoadLabel, 0, 0, 1, 1)
        self.AdThickLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdThickLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdThickLabel.setObjectName("AdThickLabel")
        self.gridLayout.addWidget(self.AdThickLabel, 2, 0, 1, 1)
        self.BaseAdThickmm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.BaseAdThickmm.setAlignment(QtCore.Qt.AlignCenter)
        self.BaseAdThickmm.setObjectName("BaseAdThickmm")
        self.gridLayout.addWidget(self.BaseAdThickmm, 3, 2, 1, 1)
        self.AdhesiveYieldStressLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveYieldStressLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdhesiveYieldStressLabel.setObjectName("AdhesiveYieldStressLabel")
        self.gridLayout.addWidget(self.AdhesiveYieldStressLabel, 10, 0, 1, 1)
        self.AdhesiveShearModulusLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveShearModulusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdhesiveShearModulusLabel.setObjectName("AdhesiveShearModulusLabel")
        self.gridLayout.addWidget(self.AdhesiveShearModulusLabel, 15, 0, 1, 1)

        self.ThroughThincknessLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ThroughThincknessLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ThroughThincknessLabel.setObjectName("ThroughThincknessLabel")
        self.gridLayout.addWidget(self.ThroughThincknessLabel, 18, 0, 1, 1)

        self.InterlaminarShearStrengthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.InterlaminarShearStrengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.InterlaminarShearStrengthLabel.setObjectName("InterlaminarShearStrengthLabel")
        self.gridLayout.addWidget(self.InterlaminarShearStrengthLabel, 19, 0, 1, 1)

        self.AdherendShearModulusLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdherendShearModulusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdherendShearModulusLabel.setObjectName("AdherendShearModulusLabel")
        self.gridLayout.addWidget(self.AdherendShearModulusLabel, 16, 0, 1, 1)

        self.AdhesiveYieldStrengthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveYieldStrengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdhesiveYieldStrengthLabel.setObjectName("AdhesiveYieldStrengthLabel")
        self.gridLayout.addWidget(self.AdhesiveYieldStrengthLabel, 17, 0, 1, 1)

        self.TopAdThickmm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TopAdThickmm.setAlignment(QtCore.Qt.AlignCenter)
        self.TopAdThickmm.setObjectName("TopAdThickmm")
        self.gridLayout.addWidget(self.TopAdThickmm, 2, 2, 1, 1)
        self.AdhesiveThickLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AdhesiveThickLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdhesiveThickLabel.setObjectName("AdhesiveThickLabel")
        self.gridLayout.addWidget(self.AdhesiveThickLabel, 7, 0, 1, 1)
        self.adModMPa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.adModMPa.setAlignment(QtCore.Qt.AlignCenter)
        self.adModMPa.setObjectName("adModMPa")
        self.gridLayout.addWidget(self.adModMPa, 1, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 520, 100))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MaxStressHartSmithLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        #ddd
        self.FailureMode1LineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.FailureMode2LineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.FailureMode3LineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        #ddd
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxStressHartSmithLineEdit.sizePolicy().hasHeightForWidth())
        self.MaxStressHartSmithLineEdit.setSizePolicy(sizePolicy)
        self.MaxStressHartSmithLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.MaxStressHartSmithLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxStressHartSmithLineEdit.setReadOnly(True)
        self.MaxStressHartSmithLineEdit.setObjectName("MaxStressHartSmithLineEdit")
        self.gridLayout_3.addWidget(self.MaxStressHartSmithLineEdit, 1, 1, 1, 1)
        self.MaxStressGolandLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxStressGolandLineEdit.sizePolicy().hasHeightForWidth())
        self.MaxStressGolandLineEdit.setSizePolicy(sizePolicy)
        self.MaxStressGolandLineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.MaxStressGolandLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxStressGolandLineEdit.setReadOnly(True)
        self.MaxStressGolandLineEdit.setObjectName("MaxStressGolandLineEdit")
        self.gridLayout_3.addWidget(self.MaxStressGolandLineEdit, 1, 3, 1, 1)

        #fff
        sizePolicy.setHeightForWidth(self.FailureMode1LineEdit.sizePolicy().hasHeightForWidth())
        self.FailureMode1LineEdit.setSizePolicy(sizePolicy)
        self.FailureMode1LineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.FailureMode1LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureMode1LineEdit.setReadOnly(True)
        self.FailureMode1LineEdit.setObjectName("FailureModeLineEdit")
        self.gridLayout_3.addWidget(self.FailureMode1LineEdit, 4, 1, 1, 1)

        sizePolicy.setHeightForWidth(self.FailureMode2LineEdit.sizePolicy().hasHeightForWidth())
        self.FailureMode2LineEdit.setSizePolicy(sizePolicy)
        self.FailureMode2LineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.FailureMode2LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureMode2LineEdit.setReadOnly(True)
        self.FailureMode2LineEdit.setObjectName("FailureModeLineEdit")
        self.gridLayout_3.addWidget(self.FailureMode2LineEdit, 4, 2, 1, 1)

        sizePolicy.setHeightForWidth(self.FailureMode3LineEdit.sizePolicy().hasHeightForWidth())
        self.FailureMode3LineEdit.setSizePolicy(sizePolicy)
        self.FailureMode3LineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.FailureMode3LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureMode3LineEdit.setReadOnly(True)
        self.FailureMode3LineEdit.setObjectName("FailureModeLineEdit")
        self.gridLayout_3.addWidget(self.FailureMode3LineEdit, 4, 3, 1, 1)

        self.FailureModeVonMisesLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.FailureModeVonMisesLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FailureModeVonMisesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureModeVonMisesLabel.setObjectName("FailureModeVonMisesLabel")
        self.gridLayout_3.addWidget(self.FailureModeVonMisesLabel, 3, 1, 1, 1)
        self.FailureModeDruckerPrager = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.FailureModeDruckerPrager.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FailureModeDruckerPrager.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureModeDruckerPrager.setObjectName("FailureModeDruckerPrager")
        self.gridLayout_3.addWidget(self.FailureModeDruckerPrager, 3, 2, 1, 1)
        self.FailureModeTsaiWu = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.FailureModeTsaiWu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FailureModeTsaiWu.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureModeTsaiWu.setObjectName("FailureModeTsaiWu")
        self.gridLayout_3.addWidget(self.FailureModeTsaiWu, 3, 3, 1, 1)

        self.FactorofSafetyHartSmithLabel = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FactorofSafetyHartSmithLabel.sizePolicy().hasHeightForWidth())
        self.FactorofSafetyHartSmithLabel.setSizePolicy(sizePolicy)
        self.FactorofSafetyHartSmithLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FactorofSafetyHartSmithLabel.setReadOnly(True)
        self.FactorofSafetyHartSmithLabel.setObjectName("FactorofSafetyHartSmithLabel")
        self.gridLayout_3.addWidget(self.FactorofSafetyHartSmithLabel, 2, 1, 1, 1)
        self.FactorofSafetyGoland = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FactorofSafetyGoland.sizePolicy().hasHeightForWidth())
        self.FactorofSafetyGoland.setSizePolicy(sizePolicy)
        self.FactorofSafetyGoland.setAlignment(QtCore.Qt.AlignCenter)
        self.FactorofSafetyGoland.setReadOnly(True)
        self.FactorofSafetyGoland.setObjectName("FactorofSafetyGoland")
        self.gridLayout_3.addWidget(self.FactorofSafetyGoland, 2, 3, 1, 1)
        self.MaxStressVolkersenLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxStressVolkersenLineEdit.sizePolicy().hasHeightForWidth())
        self.MaxStressVolkersenLineEdit.setSizePolicy(sizePolicy)
        self.MaxStressVolkersenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxStressVolkersenLineEdit.setReadOnly(True)
        self.MaxStressVolkersenLineEdit.setObjectName("MaxStressVolkersenLineEdit")
        self.gridLayout_3.addWidget(self.MaxStressVolkersenLineEdit, 1, 2, 1, 1)
        self.FactorofSafety = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FactorofSafety.setFont(font)
        self.FactorofSafety.setAlignment(QtCore.Qt.AlignCenter)
        self.FactorofSafety.setObjectName("FactorofSafety")
        self.gridLayout_3.addWidget(self.FactorofSafety, 2, 0, 1, 1)
        self.FactorofSafetyLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FactorofSafetyLineEdit.sizePolicy().hasHeightForWidth())
        self.FactorofSafetyLineEdit.setSizePolicy(sizePolicy)
        self.FactorofSafetyLineEdit.setText("")
        self.FactorofSafetyLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FactorofSafetyLineEdit.setReadOnly(True)
        self.FactorofSafetyLineEdit.setObjectName("FactorofSafetyLineEdit")
        self.gridLayout_3.addWidget(self.FactorofSafetyLineEdit, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.MaxStress = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.FailureMode = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MaxStress.setFont(font)
        self.MaxStress.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxStress.setObjectName("MaxStress")
        self.gridLayout_3.addWidget(self.MaxStress, 1, 0, 1, 1)
        #fff
        self.FailureMode.setFont(font)
        self.FailureMode.setAlignment(QtCore.Qt.AlignCenter)
        self.FailureMode.setObjectName("FailureMode")
        self.gridLayout_3.addWidget(self.FailureMode, 4, 0, 1, 1)
        self.HartSmithLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HartSmithLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.HartSmithLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HartSmithLabel.setObjectName("HartSmithLabel")
        self.gridLayout_3.addWidget(self.HartSmithLabel, 0, 1, 1, 1)
        self.VolkersenLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VolkersenLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.VolkersenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VolkersenLabel.setObjectName("VolkersenLabel")
        self.gridLayout_3.addWidget(self.VolkersenLabel, 0, 2, 1, 1)
        #SHEHAB
        self.GolandLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.GolandLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.GolandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GolandLabel.setObjectName("GolandLabel")
        self.gridLayout_3.addWidget(self.GolandLabel, 0, 3, 1, 1)
        #SHEHAB

        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(50, 10, 351, 171))
        self.Image.setAutoFillBackground(False)
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("SingleLappedJointHart-SmithSmallest.png"))
        self.Image.setScaledContents(True)
        self.Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(50, 290, 351, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.VolkersenPushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.VolkersenPushButton.setObjectName("VolkersenPushButton")
        self.gridLayout_4.addWidget(self.VolkersenPushButton, 0, 1, 1, 1)
        self.HartSmithPushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.HartSmithPushButton.setObjectName("HartSmithPushButton")
        self.gridLayout_4.addWidget(self.HartSmithPushButton, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 450, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SolveButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SolveButton.sizePolicy().hasHeightForWidth())
        self.SolveButton.setSizePolicy(sizePolicy)
        self.SolveButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SolveButton.setFont(font)
        self.SolveButton.setObjectName("SolveButton")
        self.gridLayout_2.addWidget(self.SolveButton, 0, 1, 1, 1)
        self.ClearButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearButton.sizePolicy().hasHeightForWidth())
        self.ClearButton.setSizePolicy(sizePolicy)
        self.ClearButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("ClearButton")
        self.gridLayout_2.addWidget(self.ClearButton, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(70, 320, 351, 41))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.homogenousRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.homogenousRadioButton.setChecked(True)
        self.homogenousRadioButton.setObjectName("homogenousRadioButton")
        self.gridLayout_5.addWidget(self.homogenousRadioButton, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.anistropicRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.anistropicRadioButton.setObjectName("anistropicRadioButton")
        self.gridLayout_5.addWidget(self.anistropicRadioButton, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.substrateLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.substrateLabel.setObjectName("substrateLabel")
        self.gridLayout_5.addWidget(self.substrateLabel, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.InformationBox = QtWidgets.QLabel(self.centralwidget)
        self.InformationBox.setGeometry(QtCore.QRect(50, 430, 349, 40))
        self.InformationBox.setAutoFillBackground(False)
        self.InformationBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InformationBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InformationBox.setLineWidth(2)
        self.InformationBox.setAlignment(QtCore.Qt.AlignCenter)
        self.InformationBox.setObjectName("InformationBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        self.menuAdhesives = QtWidgets.QMenu(self.menubar)
        self.menuAdhesives.setObjectName("menuAdhesives")
        self.menuAdherend_2 = QtWidgets.QMenu(self.menubar)
        self.menuAdherend_2.setObjectName("menuAdherend_2")
        self.menuJoint_Type_2 = QtWidgets.QMenu(self.menubar)
        self.menuJoint_Type_2.setObjectName("menuJoint_Type_2")

        self.menuFailureCriteria = QtWidgets.QMenu(self.menubar)
        self.menuFailureCriteria.setObjectName("menuFailureCriteria")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSingle_Lapped_Joint = QtWidgets.QAction(MainWindow)
        self.actionSingle_Lapped_Joint.setObjectName("actionSingle_Lapped_Joint")

        self.VonMises = QtWidgets.QAction(MainWindow)
        self.VonMises.setObjectName("VonMises")
        self.DruckerPrager = QtWidgets.QAction(MainWindow)
        self.DruckerPrager.setObjectName("DruckerPrager")
        self.TsaiWu = QtWidgets.QAction(MainWindow)
        self.TsaiWu.setObjectName("TsaiWu")

        self.actionAV119 = QtWidgets.QAction(MainWindow)
        self.actionAV119.setObjectName("actionAV119")
        self.actionCustom_Adhesive = QtWidgets.QAction(MainWindow)
        self.actionCustom_Adhesive.setObjectName("actionCustom_Adhesive")
        self.actionCustom_Adherend = QtWidgets.QAction(MainWindow)
        self.actionCustom_Adherend.setObjectName("actionCustom_Adherend")
        self.actionSingle_Lapped_Joint_2 = QtWidgets.QAction(MainWindow)
        self.actionSingle_Lapped_Joint_2.setObjectName("actionSingle_Lapped_Joint_2")
        self.actionDouble_Lapped_Joint = QtWidgets.QAction(MainWindow)
        self.actionDouble_Lapped_Joint.setObjectName("actionDouble_Lapped_Joint")
        self.actionAV119_2 = QtWidgets.QAction(MainWindow)
        self.actionAV119_2.setObjectName("actionAV119_2")
        self.actionAV119_3 = QtWidgets.QAction(MainWindow)
        self.actionAV119_3.setObjectName("actionAV119_3")
        self.actionCustom_Adherend_2 = QtWidgets.QAction(MainWindow)
        self.actionCustom_Adherend_2.setObjectName("actionCustom_Adherend_2")
        self.actionCustom_Adherend_3 = QtWidgets.QAction(MainWindow)
        self.actionCustom_Adherend_3.setObjectName("actionCustom_Adherend_3")
        self.actionCustom_Adhesive_2 = QtWidgets.QAction(MainWindow)
        self.actionCustom_Adhesive_2.setObjectName("actionCustom_Adhesive_2")
        self.actionSingle_Lapped_Joint_3 = QtWidgets.QAction(MainWindow)
        self.actionSingle_Lapped_Joint_3.setObjectName("actionSingle_Lapped_Joint_3")
        self.actionDouble_Lapped_Joint_2 = QtWidgets.QAction(MainWindow)
        self.actionDouble_Lapped_Joint_2.setObjectName("actionDouble_Lapped_Joint_2")
        self.actionRedux326 = QtWidgets.QAction(MainWindow)
        self.actionRedux326.setObjectName("actionRedux326")
        self.actionHysol19321 = QtWidgets.QAction(MainWindow)
        self.actionHysol19321.setObjectName("actionHysol19321")
        self.actionMildSteel = QtWidgets.QAction(MainWindow)
        self.actionMildSteel.setObjectName("actionMildSteel")
        self.actionHighStrengthSteel = QtWidgets.QAction(MainWindow)
        self.actionHighStrengthSteel.setObjectName("actionAluminiumAlloy")
        self.actionAluminium = QtWidgets.QAction(MainWindow)
        self.actionAluminium.setObjectName("actionAluminium")
        self.actionCarbonFiber = QtWidgets.QAction(MainWindow)
        self.actionCarbonFiber.setObjectName("actionCarbonFiber")
        self.menuAdhesives.addAction(self.actionAV119_3)
        self.menuAdhesives.addAction(self.actionRedux326)
        self.menuAdhesives.addAction(self.actionHysol19321)
        self.menuAdhesives.addAction(self.actionCustom_Adhesive_2)
        self.menuAdherend_2.addAction(self.actionMildSteel)
        self.menuAdherend_2.addAction(self.actionHighStrengthSteel)
        self.menuAdherend_2.addAction(self.actionAluminium)
        self.menuAdherend_2.addAction(self.actionCarbonFiber)
        self.menuAdherend_2.addAction(self.actionCustom_Adherend_2)
        self.menuJoint_Type_2.addAction(self.actionSingle_Lapped_Joint_3)
        self.menuJoint_Type_2.addAction(self.actionDouble_Lapped_Joint_2)
        self.menuFailureCriteria.addAction(self.VonMises)
        self.menuFailureCriteria.addAction(self.DruckerPrager)
        self.menuFailureCriteria.addAction(self.TsaiWu)
        self.menubar.addAction(self.menuAdhesives.menuAction())
        self.menubar.addAction(self.menuAdherend_2.menuAction())
        self.menubar.addAction(self.menuJoint_Type_2.menuAction())
        self.menubar.addAction(self.menuFailureCriteria.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LoadLineEdit, self.AdModLineEdit)
        MainWindow.setTabOrder(self.AdModLineEdit, self.TopAdThickLineEdit)
        MainWindow.setTabOrder(self.TopAdThickLineEdit, self.BaseAdThickLineEdit)
        MainWindow.setTabOrder(self.BaseAdThickLineEdit, self.PRatioLineEdit)
        MainWindow.setTabOrder(self.PRatioLineEdit, self.OverlapLengthLineEdit)
        MainWindow.setTabOrder(self.OverlapLengthLineEdit, self.AdhesiveThickLineEdit)
        MainWindow.setTabOrder(self.AdhesiveThickLineEdit, self.AdShearModLineEdit)
        MainWindow.setTabOrder(self.AdShearModLineEdit, self.JointWidthLineEdit)
        MainWindow.setTabOrder(self.JointWidthLineEdit, self.HartSmithPushButton)
        MainWindow.setTabOrder(self.HartSmithPushButton, self.VolkersenPushButton)
        MainWindow.setTabOrder(self.VolkersenPushButton, self.ClearButton)
        MainWindow.setTabOrder(self.ClearButton, self.SolveButton)
        MainWindow.setTabOrder(self.SolveButton, self.MaxStressHartSmithLineEdit)
        MainWindow.setTabOrder(self.MaxStressHartSmithLineEdit, self.FactorofSafetyHartSmithLabel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SubstrateYieldStressLabel_2.setText(_translate("MainWindow", " "))
        self.JointWidthLabel.setText(_translate("MainWindow", "Joint Width, B"))
        self.OverlapLengthmm.setText(_translate("MainWindow", "mm"))
        self.JointWidtmm.setText(_translate("MainWindow", "mm"))
        self.AdShearModGPa.setText(_translate("MainWindow", "GPa"))
        self.AdThickLabel_2.setText(_translate("MainWindow", "Base Adherend Thickness, t2"))
        self.SubstrateYieldStressMPa_2.setText(_translate("MainWindow", "MPa"))
        self.AdhesiveYieldStressMPa.setText(_translate("MainWindow", "MPa"))
        self.AdhesiveYieldStressLabel.setText(_translate("MainWindow", "Adhesive Shear Strength"))
        self.AdhesiveShearModulusMPa.setText(_translate("MainWindow", "GPa"))
        self.ThroughThincknessMPa.setText(_translate("MainWindow", "MPa"))
        self.InterlaminarShearStrengthMPa.setText(_translate("MainWindow", "MPa"))
        self.AdherendShearModulusMPa.setText(_translate("MainWindow", "GPa"))
        self.AdhesiveYieldStrengthMPa.setText(_translate("MainWindow", "MPa"))
        self.label.setText(_translate("MainWindow", " "))
        self.PRatioLabel.setText(_translate("MainWindow", "Poisson\'s Ratio, v"))
        self.AdShearModLabel.setText(_translate("MainWindow", "Adhesive Young\'s Modulus, G"))
        self.SubstrateYieldStressMPa_3.setText(_translate("MainWindow", "MPa"))
        self.AdhesiveThickmm.setText(_translate("MainWindow", "mm"))
        self.OverlapLengthLabel.setText(_translate("MainWindow", "Overlap Length, L"))
        self.AdModLabel.setText(_translate("MainWindow", "Adherend Young\'s Modulus, E"))
        self.SubstrateYieldStressMPa.setText(_translate("MainWindow", "MPa"))
        self.LoadN.setText(_translate("MainWindow", "N"))
        self.SubstrateYieldStressLabel.setText(_translate("MainWindow", "Substrate Yield Strength"))
        self.LoadLabel.setText(_translate("MainWindow", "Load, P"))
        self.AdThickLabel.setText(_translate("MainWindow", "Top Adherend Thickness, t1"))
        self.BaseAdThickmm.setText(_translate("MainWindow", "mm"))
        self.AdhesiveShearModulusLabel.setText(_translate("MainWindow", "Adhesive Shear Modulus, G1"))
        self.AdherendShearModulusLabel.setText(_translate("MainWindow", "Adherend Shear Modulus, G2"))
        self.AdhesiveYieldStrengthLabel.setText(_translate("MainWindow", "Adhesive Yield Strength, Syt"))
        self.ThroughThincknessLabel.setText(_translate("MainWindow", "Through Thinckness, X"))
        self.InterlaminarShearStrengthLabel.setText(_translate("MainWindow", "Inter laminar Shear Strength, S"))
        self.TopAdThickmm.setText(_translate("MainWindow", "mm"))
        self.AdhesiveThickLabel.setText(_translate("MainWindow", "Adhesive Thickness, T"))
        self.adModMPa.setText(_translate("MainWindow", "GPa"))
        self.FactorofSafety.setText(_translate("MainWindow", "Peel"))
        self.MaxStress.setText(_translate("MainWindow", "Shear"))
        self.FailureMode.setText(_translate("MainWindow", "Failure Criteria"))
        self.HartSmithLabel.setText(_translate("MainWindow", "Hart-Smith"))
        self.VolkersenLabel.setText(_translate("MainWindow", "Volkersen"))
        self.FailureModeVonMisesLabel.setText(_translate("MainWindow", "Von Mises"))
        self.FailureModeDruckerPrager.setText(_translate("MainWindow", "Drucker Prager"))
        self.FailureModeTsaiWu.setText(_translate("MainWindow", "Tsai Wu"))
        self.GolandLabel.setText(_translate("MainWindow", "Adams (Pa,Ps)"))
        self.VolkersenPushButton.setText(_translate("MainWindow", "Volkersen\'s Analysis"))
        self.HartSmithPushButton.setText(_translate("MainWindow", "Hart-Smith Analysis"))
        self.SolveButton.setText(_translate("MainWindow", "Solve"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.homogenousRadioButton.setText(_translate("MainWindow", "Homogenous"))
        self.anistropicRadioButton.setText(_translate("MainWindow", "Aniostropic"))
        self.substrateLabel.setText(_translate("MainWindow", "Substrate Type:"))
        self.InformationBox.setText(_translate("MainWindow", "Application Ready!"))
        self.menuAdhesives.setTitle(_translate("MainWindow", "Adhesives"))
        self.menuAdherend_2.setTitle(_translate("MainWindow", "Adherend"))
        self.menuJoint_Type_2.setTitle(_translate("MainWindow", "Joint Type"))
        self.menuFailureCriteria.setTitle(_translate("MainWindow", "Failure Criteria"))
        self.VonMises.setText(_translate("MainWindow", "Von Mises"))
        self.DruckerPrager.setText(_translate("MainWindow", "Drucker Prager"))
        self.TsaiWu.setText(_translate("MainWindow", "Tsai Wu"))
        self.actionSingle_Lapped_Joint.setText(_translate("MainWindow", "Single Lapped Joint"))
        self.actionAV119.setText(_translate("MainWindow", "AV119"))
        self.actionCustom_Adhesive.setText(_translate("MainWindow", "Custom Adhesive"))
        self.actionCustom_Adherend.setText(_translate("MainWindow", "Custom Adherend"))
        self.actionSingle_Lapped_Joint_2.setText(_translate("MainWindow", "Single Lapped Joint"))
        self.actionDouble_Lapped_Joint.setText(_translate("MainWindow", "Double Lapped Joint"))
        self.actionAV119_2.setText(_translate("MainWindow", "AV119"))
        self.actionAV119_3.setText(_translate("MainWindow", "AV119"))
        self.actionCustom_Adherend_2.setText(_translate("MainWindow", "Custom Adherend"))
        self.actionCustom_Adherend_3.setText(_translate("MainWindow", "Custom Adherend"))
        self.actionCustom_Adhesive_2.setText(_translate("MainWindow", "Custom Adhesive"))
        self.actionSingle_Lapped_Joint_3.setText(_translate("MainWindow", "Single Lapped Joint"))
        self.actionDouble_Lapped_Joint_2.setText(_translate("MainWindow", "Double Lapped Joint"))
        self.actionRedux326.setText(_translate("MainWindow", "Redux326"))
        self.actionHysol19321.setText(_translate("MainWindow", "Hysol19321"))
        self.actionMildSteel.setText(_translate("MainWindow", "MildSteel"))
        self.actionHighStrengthSteel.setText(_translate("MainWindow", "Aluminium Alloy"))
        self.actionAluminium.setText(_translate("MainWindow", "Aluminium"))
        self.actionCarbonFiber.setText(_translate("MainWindow", "CarbonFiber"))
